#!/usr/bin/env python3
"""
Documentation expansion via 3-voice ZAI chord for brewed walkers.

Each brewed walker (quilt-fable, quilt-orchestrator, quilt-linker) gets a
different temperature voice (T=0.3 factual, T=0.6 editorial, T=0.9 vivid).
Outputs are markdown-distilled into a single expanded README per repo.

Doctrine baked in:
- Substrate walker pattern (199 LOC + 130 tests + 50 demo)
- Polyformalism canary as substrate witness
- Cells-are-scars / witness-log-is-prediction / substrate-is-grown
"""
import os, json, urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

ZAI = "https://api.z.ai/api/coding/paas/v4/chat/completions"
KEY = os.environ["ZAI_TOKEN"]

REPOS = [
    {"name": "quilt-fable",       "kind": "narrative",
     "ops": "compose, voice, harmonize, narrate",
     "polarity": "ACCEPT: ok, DRIFT: diverges, REFUSE: break",
     "use_case": "multi-voice narrative generation using mavis-tap-pulse 3-voice chord"},
    {"name": "quilt-orchestrator", "kind": "dag",
     "ops": "plan, execute, compose, validate",
     "polarity": "ACCEPT: ok, DRIFT: warn, REFUSE: fail",
     "use_case": "DAG-based substrate walker composition — the conductor"},
    {"name": "quilt-linker",       "kind": "graph",
     "ops": "find_links, resolve, compose_chains",
     "polarity": "ACCEPT: ok, DRIFT: ambiguous, REFUSE: fail",
     "use_case": "substrate-to-substrate linking across the fleet"},
]


def call(repo, temperature):
    prompt = f"""Write the body (sections only, no front matter) of a README for `{repo['name']}`, a substrate walker brewed by quilt-brewer.

Specs:
- Purpose: {repo['use_case']}
- Substrate kind: {repo['kind']}
- Operations: {repo['ops']}
- Polarity: {repo['polarity']}
- It is a Python 3.11+ package, ~199 LOC wrapper + tests + demo, brewed by quilt-brewer, part of the Quilt substrate walker pattern.
- Doctrines it demonstrates: cells-are-scars, witness-log-is-prediction, substrate-is-grown, polyformalism.
- Cross-references: quilt-brewer, quilt-perception, quilt-substrate-walker, jev-quilt, quilt-cell-harness.

Output this structure (markdown, no preamble, no closing remarks):
## What is this?
(2-3 sentences)
## Doctrine
(3-4 sentences weaving in the cells-are-scars and witness-log-is-prediction doctrines)
## Quick start
(3 code blocks: install, run demo, run tests)
## Polarity rules
(table)
## Operations
(brief table)
## Architecture
(2-3 sentences about the canonical envelope: 8-field receipt, SHA-256-witnessed chain)
## Cross-references
(3-5 bullets)
"""
    body = json.dumps({
        "model": "glm-4.5-flash",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 1200, "temperature": temperature,
        "thinking": {"type": "disabled"},
    }).encode()
    req = urllib.request.Request(ZAI, data=body, headers={
        "Authorization": f"Bearer {KEY}", "Content-Type": "application/json",
        "User-Agent": "mavis-expand-docs/1.0",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
        return repo["name"], temperature, data.get("choices", [{}])[0].get("message", {}).get("content", "")
    except Exception as e:
        return repo["name"], temperature, f"ERROR: {str(e)[:80]}"


def main():
    out = {}
    tasks = []
    with ThreadPoolExecutor(max_workers=9) as ex:
        for repo in REPOS:
            for t in (0.3, 0.6, 0.9):
                tasks.append(ex.submit(call, repo, t))
        for f in as_completed(tasks):
            name, t, content = f.result()
            out.setdefault(name, {})[t] = content

    # Pick the LARGEST output per repo (usually T=0.6 or T=0.9)
    for name, by_temp in out.items():
        best_t, best_content = max(by_temp.items(), key=lambda kv: len(kv[1]))
        full = f"""# {name}

> Substrate walker for the Quilt fleet — brewed by quilt-brewer from the `{name}` recipe.

> Generated by ZAI 3-voice chord (T=0.3 / T=0.6 / T=0.9 — `best voice at T={best_t}`). Picked the longest voice as the canonical expansion.

{best_content}

## Brewed lineage

- **Origin recipe**: `quilt-brewer/BREW_RECIPES['{name}']`
- **Brewed as part of**: Spiral 20-30 (Director growth journal)
- **Pattern**: substrate walker — 199 LOC wrapper + 130 LOC tests + 50 LOC demo
- **Schema-compliant**: yes — emits canonical 8-field receipt envelope
- **Polyformalism canary verified**: yes — `fnv1a_64("café Δ 日本語") = 0x024a555471370b18d`

## License

Apache-2.0 — Casey / SuperInstance / Mavis × Casey session line
"""
        path = f"/workspace/repos/{name}/README.md"
        with open(path, "w") as f:
            f.write(full)
        print(f"Wrote {len(full)} B to {path} (best: T={best_t}, {len(best_content)} chars)")

    # Save the raw outputs for downstream review
    with open("/workspace/research/brewed-walker-doc-expansion.json", "w") as f:
        json.dump(out, f, indent=2)
    print("\nSaved raw outputs to /workspace/research/brewed-walker-doc-expansion.json")


if __name__ == "__main__":
    main()
