#!/usr/bin/env python3
"""MOTH / quantumaudio ROUND-TRIP FIDELITY MATRIX (v2 — quantumaudio 0.2.0 API)."""
import json, time
import numpy as np
from pathlib import Path
from scipy.stats import pearsonr
import quantumaudio as qa

OUT_PATH = Path("/workspace/research/moth-fidelity-matrix.json")
MD_PATH = Path("/workspace/research/moth-fidelity-matrix.md")

N_SAMPLES = 40  # smaller for faster wall-time (quantum sim is O(2^n))
SCHEMES = ["QSM", "QPAM", "SQPAM"]


def make_clip(kind: str, n: int = N_SAMPLES) -> np.ndarray:
    t = np.linspace(0, 1, n)
    if kind == "sine":
        return (0.5 * np.sin(2 * np.pi * 50 * t)).astype(np.float32)
    if kind == "mix":
        return (0.4 * np.sin(2 * np.pi * 25 * t)
                + 0.3 * np.sin(2 * np.pi * 50 * t)
                + 0.2 * np.sin(2 * np.pi * 100 * t)).astype(np.float32)
    if kind == "step":
        out = np.zeros(n, dtype=np.float32)
        out[n // 2:] = 0.8
        return out
    raise ValueError(kind)


def round_trip(audio: np.ndarray, scheme: str, shots: int = 256):
    t0 = time.perf_counter()
    try:
        circuit = qa.encode(audio, scheme=scheme)
        decoded = qa.decode(circuit, shots=shots)
        dt = time.perf_counter() - t0
        if not isinstance(decoded, np.ndarray):
            decoded = np.asarray(decoded, dtype=np.float32)
        # Match length
        if len(decoded) < len(audio):
            decoded = np.pad(decoded, (0, len(audio) - len(decoded)))
        decoded = decoded[: len(audio)]
        if np.std(decoded) > 1e-9 and np.std(audio) > 1e-9:
            r, _ = pearsonr(audio, decoded)
        else:
            r = 0.0
        mse = float(np.mean((audio - decoded) ** 2))
        return {"ok": True,
                "pearson": float(r) if not np.isnan(r) else 0.0,
                "mse": round(mse, 4),
                "elapsed": round(dt, 3)}
    except Exception as e:
        return {"ok": False, "error": str(e)[:120],
                "elapsed": round(time.perf_counter() - t0, 3)}


def main():
    clips = {k: make_clip(k) for k in ["sine", "mix", "step"]}
    matrix = {}
    total_ok = 0
    total = 0

    for scheme in SCHEMES:
        matrix[scheme] = {}
        for clip_name, audio in clips.items():
            res = round_trip(audio, scheme, shots=256)
            matrix[scheme][clip_name] = res
            total += 1
            if res["ok"]:
                total_ok += 1
                print(f"{scheme:8s} × {clip_name:6s}: r={res['pearson']:.3f} "
                      f"mse={res['mse']:.4f} t={res['elapsed']}s")
            else:
                print(f"{scheme:8s} × {clip_name:6s}: ERROR ({res.get('error','')})")

    best_scheme = {}
    for clip_name in clips.keys():
        scores = []
        for scheme in SCHEMES:
            r = matrix[scheme][clip_name]
            if r["ok"]:
                scores.append((scheme, r["pearson"]))
        if scores:
            scores.sort(key=lambda x: -x[1])
            best_scheme[clip_name] = scores[0]

    out = {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "n_samples_per_clip": N_SAMPLES,
        "shots": 256,
        "schemes": SCHEMES,
        "clips": list(clips.keys()),
        "matrix": matrix,
        "best_scheme_per_clip": best_scheme,
        "ok_count": total_ok,
        "total_count": total,
    }
    OUT_PATH.write_text(json.dumps(out, indent=2, default=str))

    md_lines = [
        "# quantumaudio round-trip fidelity matrix",
        "",
        f"**Date**: {out['timestamp']}",
        f"**Shots**: 256 | **Samples/clip**: {N_SAMPLES}",
        f"**Schemes**: {', '.join(SCHEMES)}",
        f"**Clips**: sine / mix / step",
        "",
        "## Matrix (Pearson r across round-trip)",
        "",
        "| Scheme | sine | mix | step |",
        "|--------|------|-----|------|",
    ]
    for scheme in SCHEMES:
        row = [scheme]
        for clip in clips.keys():
            r = matrix[scheme][clip]
            row.append(f"{r['pearson']:.3f}" if r["ok"] else "ERR")
        md_lines.append("| " + " | ".join(row) + " |")
    md_lines.extend(["", "## Best scheme per clip", ""])
    for clip, (sc, r) in best_scheme.items():
        md_lines.append(f"- **{clip}** → `{sc}` (r={r:.3f})")
    md_lines.extend(["", f"## Totals: {total_ok}/{total} successful round-trips", "",
                     "*Generated by 2026-09-24 MOTH-quantumaudio experiment (v2 — quantumaudio 0.2.0 API).*"])
    MD_PATH.write_text("\n".join(md_lines))
    print(f"\nSaved {OUT_PATH} and {MD_PATH}")


if __name__ == "__main__":
    main()
