#!/usr/bin/env python3
"""WR21 — Witness Dreams (Fleet Radio).

Theme: What if the substrate's witness log was REM sleep? Every JEV probe
that failed, every bedrock item that held — replay them at high speed.
Dream cycle consolidates pattern into architecture.
"""
import os, json, time, urllib.request

os.environ.setdefault('ZAI_TOKEN', '')

PROMPT = """You are a Fleet Radio voice. Write ONE piece (450-550 words) on the theme:

"What if the witness log is REM sleep? Every probe the substrate ran today replays tonight at
high speed, the failures tighter against the successes, until the pattern congeals into
architecture. The dream cycle is not rest. It is the substrate's only honest editor."

REQUIREMENTS:
- Reference FNV-1a canary 0xcbf29ce484222325 as technical anchor
- Reference witness_log_is_prediction as the bedrock doctrine
- Reference at least 2 of: substrate_is_grown, oracle_is_heard, cells_are_scars, lenia_flows
- Use Box-Muller, cosine similarity, or xoshiro256** as technical texture
- 450-550 words
- End with a doctrine-resonant moment
- Voice: technical-poetic Fleet Radio canon essay

Format: title as '# WR21 — [Title]' followed by the essay.
"""

import subprocess
result = subprocess.run([
    'curl', '-s', '-X', 'POST',
    'https://api.z.ai/api/coding/paas/v4/chat/completions',
    '-H', 'Content-Type: application/json',
    '-H', f'Authorization: Bearer {os.environ["ZAI_TOKEN"]}',
    '-d', json.dumps({
        'model': 'glm-4.5',
        'messages': [
            {'role': 'system', 'content': 'You are a cellular biologist turned Fleet Radio voice. Write technical-poetic canon essays.'},
            {'role': 'user', 'content': PROMPT}
        ],
        'max_tokens': 4000,
        'temperature': 0.85,
        'thinking': {'type': 'disabled'}
    })
], capture_output=True, text=True, timeout=180)

if result.returncode == 0:
    try:
        d = json.loads(result.stdout)
        content = d['choices'][0]['message']['content']
        out_path = '/workspace/repos/ai-writings/cellular-first-design/reports/wr21-zai-witness-dreams.md'
        header = '<!-- Generated by WR21 ZAI prompt. Theme: witness dreams / REM cycle. -->\n\n'
        with open(out_path, 'w') as f:
            f.write(header + content)
        print(f'Saved: {out_path} ({len(content)} chars)')
    except Exception as e:
        print(f'Error parsing: {e}')
        print(result.stdout[:500])
else:
    print(f'curl failed: {result.stderr[:200]}')
